ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,6 +2,7 @@ name: test
 on:
   push:
     branches:
+      - 'debug*'
       - 'master'
       - 'release-[0-9]+.[0-9]+'
   pull_request:
@@ -23,78 +24,78 @@ env:
   NVIM_LOG_FILE: ${{ github.workspace }}/build/.nvimlog
   TSAN_OPTIONS: log_path=${{ github.workspace }}/build/log/tsan
   VALGRIND_LOG: ${{ github.workspace }}/build/log/valgrind-%p.log
-  # TEST_FILE: test/functional/core/startup_spec.lua
+  TEST_FILE: test/functional/terminal/scrollback_spec.lua
   # TEST_FILTER: foo
 
 jobs:
-  lint:
-    runs-on: ubuntu-24.04
-    timeout-minutes: 10
-    env:
-      CC: clang
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup
+  # lint:
+  #   runs-on: ubuntu-24.04
+  #   timeout-minutes: 10
+  #   env:
+  #     CC: clang
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/setup
+  #
+  #     - name: Install stylua
+  #       run: |
+  #         wget --directory-prefix="$BIN_DIR" https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
+  #         (cd "$BIN_DIR"; unzip stylua*.zip)
+  #
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps -B .deps -G Ninja
+  #         cmake --build .deps
+  #
+  #     - run: cmake -B build -G Ninja -D CI_LINT=ON
+  #
+  #     - if: "!cancelled()"
+  #       name: Determine if run should be aborted
+  #       id: abort_job
+  #       run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: stylua
+  #       run: cmake --build build --target lintlua-stylua
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: luals
+  #       run: cmake --build build --target luals
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: luacheck
+  #       run: cmake --build build --target lintlua-luacheck
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: lintsh
+  #       run: cmake --build build --target lintsh
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: clint.py
+  #       run: cmake --build build --target lintc-clint
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: clang-tidy
+  #       run: cmake --build build --target lintc-clang-tidy
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: uncrustify
+  #       run: cmake --build build --target lintc-uncrustify
 
-      - name: Install stylua
-        run: |
-          wget --directory-prefix="$BIN_DIR" https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
-          (cd "$BIN_DIR"; unzip stylua*.zip)
-
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps -B .deps -G Ninja
-          cmake --build .deps
-
-      - run: cmake -B build -G Ninja -D CI_LINT=ON
-
-      - if: "!cancelled()"
-        name: Determine if run should be aborted
-        id: abort_job
-        run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: stylua
-        run: cmake --build build --target lintlua-stylua
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: luals
-        run: cmake --build build --target luals
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: luacheck
-        run: cmake --build build --target lintlua-luacheck
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: lintsh
-        run: cmake --build build --target lintsh
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: clint.py
-        run: cmake --build build --target lintc-clint
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: clang-tidy
-        run: cmake --build build --target lintc-clang-tidy
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: uncrustify
-        run: cmake --build build --target lintc-uncrustify
-
-  clang-analyzer:
-    runs-on: ubuntu-24.04
-    timeout-minutes: 20
-    env:
-      CC: clang
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps --preset ci
-          cmake --build .deps
-          cmake --preset ci
-      - run: cmake --build build --target clang-analyzer
+  # clang-analyzer:
+  #   runs-on: ubuntu-24.04
+  #   timeout-minutes: 20
+  #   env:
+  #     CC: clang
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/setup
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps --preset ci
+  #         cmake --build .deps
+  #         cmake --preset ci
+  #     - run: cmake --build build --target clang-analyzer
 
   posix:
     name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
@@ -116,7 +117,8 @@ jobs:
             { runner: macos-15, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
             { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
           ]
-        test: [unittest, functionaltest, oldtest]
+        # test: [unittest, functionaltest, oldtest]
+        test: [functionaltest]
         exclude:
           - test: unittest
             build: { flavor: tsan }
