ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,6 +2,7 @@ name: test
 on:
   push:
     branches:
+      - 'debug*'
       - 'master'
       - 'release-[0-9]+.[0-9]+'
   pull_request:
@@ -23,7 +24,7 @@ env:
   NVIM_LOG_FILE: ${{ github.workspace }}/build/.nvimlog
   TSAN_OPTIONS: log_path=${{ github.workspace }}/build/log/tsan
   VALGRIND_LOG: ${{ github.workspace }}/build/log/valgrind-%p.log
-  # TEST_FILE: test/functional/core/startup_spec.lua
+  TEST_FILE: test/functional/plugin/health_spec.lua
   # TEST_FILTER: foo
 
 jobs:
@@ -96,110 +97,110 @@ jobs:
           cmake --preset ci
       - run: cmake --build build --target clang-analyzer
 
-  posix:
-    name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
-    strategy:
-      fail-fast: false
-      matrix:
-        # The `os` field is not needed to differentiate between the different
-        # matrix builds. It is needed to not change the required checks (which
-        # uses jobs names) each time we bump the runner version. It may be
-        # possible to remove if we e.g. start using `-latest` runner versions
-        # or if github introduces a wildcard for required checks in the future.
-        build:
-          [
-            { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
-            # { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: gcc, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
-            { runner: macos-13, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
-            { runner: macos-15, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
-          ]
-        test: [unittest, functionaltest, oldtest]
-        exclude:
-          - test: unittest
-            build: { flavor: tsan }
-          - test: unittest
-            build: { flavor: puc-lua }
-          - test: oldtest
-            build: { flavor: tsan }
-    runs-on: ${{ matrix.build.runner }}
-    timeout-minutes: 45
-    env:
-      CC: ${{ matrix.build.cc }}
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup
-        with:
-          install_flags: "--test"
-
-      - name: Create log dir
-        run: mkdir -p "$LOG_DIR"
-
-      - if: ${{ matrix.test != 'unittest' }}
-        name: Set up interpreter packages
-        run: |
-          echo "Install neovim RubyGem."
-          gem install --no-document --bindir "$BIN_DIR" --user-install --pre neovim
-
-          sudo cpanm -n Neovim::Ext || cat "$HOME/.cpanm/build.log"
-          perl -W -e 'use Neovim::Ext; print $Neovim::Ext::VERSION'
-
-      - name: Remove .git directory
-        if: ${{ matrix.build.os == 'ubuntu' }}
-        run: cmake -E rm -rf -- .git
-
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps --preset ci -D CMAKE_BUILD_TYPE=Debug ${{ matrix.build.deps_flags }}
-          cmake --build .deps
-
-      - name: Build
-        run: |
-          cmake --preset ci -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_PREFIX ${{ matrix.build.flags }}
-          cmake --build build
-
-      - if: ${{ matrix.test == 'oldtest' }}
-        name: ${{ matrix.test }}
-        timeout-minutes: 20
-        run: make -C test/old/testdir NVIM_PRG=$(realpath build)/bin/nvim
-
-      - if: ${{ matrix.test != 'oldtest' }}
-        name: ${{ matrix.test }}
-        timeout-minutes: 20
-        run: cmake --build build --target ${{ matrix.test }}
-
-      - name: Install
-        run: |
-          cmake --install build
-          "$INSTALL_PREFIX/bin/nvim" --version
-          if ! "$INSTALL_PREFIX/bin/nvim" -u NONE -e -c ':help' -c ':qall'; then
-            echo "Running ':help' in the installed nvim failed."
-            echo "Maybe the helptags have not been generated properly."
-            echo 'Failed running :help'
-            exit 1
-          fi
-
-          # Check that all runtime files were installed
-          for file in $(git -C runtime ls-files '*.vim' '*.ps' '*.dict' '*.py' '*.tutor' '*.awk' '*.sh' '*.bat'); do
-            if ! test -e "$INSTALL_PREFIX/share/nvim/runtime/$file"; then
-              printf "It appears that %s is not installed." "$file"
-              exit 1
-            fi
-          done
-
-          # Check that generated syntax file has function names, #5060.
-          genvimsynf=syntax/vim/generated.vim
-          gpat='syn keyword vimFuncName .*eval'
-          if ! grep -q "$gpat" "$INSTALL_PREFIX/share/nvim/runtime/$genvimsynf"; then
-            echo "It appears that $genvimsynf does not contain $gpat."
-            exit 1
-          fi
-
-      - if: '!cancelled()'
-        name: Show logs
-        run: cat $(find "$LOG_DIR" -type f)
+  # posix:
+  #   name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # The `os` field is not needed to differentiate between the different
+  #       # matrix builds. It is needed to not change the required checks (which
+  #       # uses jobs names) each time we bump the runner version. It may be
+  #       # possible to remove if we e.g. start using `-latest` runner versions
+  #       # or if github introduces a wildcard for required checks in the future.
+  #       build:
+  #         [
+  #           { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
+  #           { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
+  #           { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
+  #           # { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: gcc, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
+  #           { runner: macos-13, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+  #           { runner: macos-15, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+  #           { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
+  #         ]
+  #       test: [unittest, functionaltest, oldtest]
+  #       exclude:
+  #         - test: unittest
+  #           build: { flavor: tsan }
+  #         - test: unittest
+  #           build: { flavor: puc-lua }
+  #         - test: oldtest
+  #           build: { flavor: tsan }
+  #   runs-on: ${{ matrix.build.runner }}
+  #   timeout-minutes: 45
+  #   env:
+  #     CC: ${{ matrix.build.cc }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/setup
+  #       with:
+  #         install_flags: "--test"
+  #
+  #     - name: Create log dir
+  #       run: mkdir -p "$LOG_DIR"
+  #
+  #     - if: ${{ matrix.test != 'unittest' }}
+  #       name: Set up interpreter packages
+  #       run: |
+  #         echo "Install neovim RubyGem."
+  #         gem install --no-document --bindir "$BIN_DIR" --user-install --pre neovim
+  #
+  #         sudo cpanm -n Neovim::Ext || cat "$HOME/.cpanm/build.log"
+  #         perl -W -e 'use Neovim::Ext; print $Neovim::Ext::VERSION'
+  #
+  #     - name: Remove .git directory
+  #       if: ${{ matrix.build.os == 'ubuntu' }}
+  #       run: cmake -E rm -rf -- .git
+  #
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps --preset ci -D CMAKE_BUILD_TYPE=Debug ${{ matrix.build.deps_flags }}
+  #         cmake --build .deps
+  #
+  #     - name: Build
+  #       run: |
+  #         cmake --preset ci -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_PREFIX ${{ matrix.build.flags }}
+  #         cmake --build build
+  #
+  #     - if: ${{ matrix.test == 'oldtest' }}
+  #       name: ${{ matrix.test }}
+  #       timeout-minutes: 20
+  #       run: make -C test/old/testdir NVIM_PRG=$(realpath build)/bin/nvim
+  #
+  #     - if: ${{ matrix.test != 'oldtest' }}
+  #       name: ${{ matrix.test }}
+  #       timeout-minutes: 20
+  #       run: cmake --build build --target ${{ matrix.test }}
+  #
+  #     - name: Install
+  #       run: |
+  #         cmake --install build
+  #         "$INSTALL_PREFIX/bin/nvim" --version
+  #         if ! "$INSTALL_PREFIX/bin/nvim" -u NONE -e -c ':help' -c ':qall'; then
+  #           echo "Running ':help' in the installed nvim failed."
+  #           echo "Maybe the helptags have not been generated properly."
+  #           echo 'Failed running :help'
+  #           exit 1
+  #         fi
+  #
+  #         # Check that all runtime files were installed
+  #         for file in $(git -C runtime ls-files '*.vim' '*.ps' '*.dict' '*.py' '*.tutor' '*.awk' '*.sh' '*.bat'); do
+  #           if ! test -e "$INSTALL_PREFIX/share/nvim/runtime/$file"; then
+  #             printf "It appears that %s is not installed." "$file"
+  #             exit 1
+  #           fi
+  #         done
+  #
+  #         # Check that generated syntax file has function names, #5060.
+  #         genvimsynf=syntax/vim/generated.vim
+  #         gpat='syn keyword vimFuncName .*eval'
+  #         if ! grep -q "$gpat" "$INSTALL_PREFIX/share/nvim/runtime/$genvimsynf"; then
+  #           echo "It appears that $genvimsynf does not contain $gpat."
+  #           exit 1
+  #         fi
+  #
+  #     - if: '!cancelled()'
+  #       name: Show logs
+  #       run: cat $(find "$LOG_DIR" -type f)
 
   windows:
     uses: ./.github/workflows/test_windows.yml
